############### NETWORKS ###############
networks:
    subnet:
        driver: bridge

############### SERVICES ###############
include:
    # --> database services
    - compose/mariadb.yml
    - compose/postgresql.yml

    # --> infrastructure
    - compose/traefik.yml

    # --> Web applications
    - compose/wordpress.yml